Cubature benchmark: cb::Builder Class Reference
cb::Builder Class Reference abstract
Common class for all builders.
#include <Builder.h>
Public Member Functions
virtual void parseParameter (const std::string &name, const std::string &value)=0
Set a parameter.
virtual void parseDefinition (const Definition &definition)
Setup builder using a definition.
Detailed Description
Common class for all builders.
Member Function Documentation
void cb::Builder::parseDefinition (const Definition & definition) virtual
Setup builder using a definition.
Parse multiple definitions in one go. This function will call parseParameter for each parameter found in the passed definition. Overload this in your subclass if you need more complex definition handling.
Parameters
definition Definition object
References cb::Definition::getParameters(), and parseParameter().
virtual void cb::Builder::parseParameter (const std::string & name, const std::string & value) pure virtual
Set a parameter.
An implementing function should parse the provided value and name string.
Parameters
name Parameter name string
value Parameter value string
Exceptions
InvalidNameError No parameter exists with the given name
InvalidValueError Parsed value is invalid (i.e. out of range)
Implemented in cb::RandomFunctorBuilder, cb::RD28Builder, cb::RD29Builder, cb::RD31Builder, cb::RD35Builder, cb::FullViewBuilder, cb::TestpackViewBuilder, cb::RawViewBuilder, and cb::HistogramViewBuilder.
Referenced by parseDefinition().
The documentation for this class was generated from the following files:
src/cubmark/Builder.h
src/Builder.cpp