Cubature benchmark: cb::RandomFunctorBuilder Class Reference
cb::RandomFunctorBuilder Class Reference abstract
Public Member Functions
~RandomFunctorBuilder ()
Destructor.
const Boundary & getDefaultBoundary ()
Get default boundary for this functor.
virtual Method::IntegrandType create ()
Create an Adapter with the functor.
virtual void parseParameter (const std::string &name, const std::string &value)
Set a parameter.
virtual RandomFunctorBuilder & exponent (double exponent)
Exponent parameter.
virtual RandomFunctorBuilder & difficulty (double difficulty)
Difficulty parameter.
Public Member Functions inherited from cb::TestFunctorBuilder
virtual double integral (const Boundary &region=Boundary())=0
Calculate the analytic value of the function's integral.
Public Member Functions inherited from cb::Builder
virtual void parseDefinition (const Definition &definition)
Setup builder using a definition.
Protected Member Functions
RandomFunctorBuilder (const Boundary &defaultBoundary=Boundary())
Constructor.
virtual RandomFunctorBuilder & R (double R)
Set R parameter.
virtual RandomFunctorBuilder & C (double C, unsigned long dim)
Set a scaling parameter.
virtual RandomFunctorBuilder & x0 (double x0, unsigned long dim)
Set a DPS parameter.
void randomizeParameters ()
Randomize parameters.
void scaleParameters ()
Divide all parameters by the difficulty factor.
virtual void setupAdapter ()=0
double difficultyFactor () const
Calculate the current difficulty factor.
Protected Attributes
double dR
General purpose parameter.
double dC [2]
Scaling vector.
double dx0 [2]
Point of Symmetry.
Boundary defaultBoundary
Default boundary.
AdapterBase< double, double, double > * ftorAdapter
Functor adapter.
Private Attributes
double dExponent
double dDifficulty
std::uniform_real_distribution< double > random01
Static Private Attributes
static const std::string parameterNames []
Constructor & Destructor Documentation
cb::RandomFunctorBuilder::RandomFunctorBuilder (const Boundary & defaultBoundary = Boundary()) protected
Constructor.
Parameters
defaultBoundary
References dC, defaultBoundary, dx0, and cb::Boundary::isValid().
Member Function Documentation
Method::IntegrandType cb::RandomFunctorBuilder::create () virtual
Create an Adapter with the functor.
Returns
Pointer to Adapter (and it's ownership)
Exceptions
IncompleteError At least one required parameter is missing.
Implements cb::TestFunctorBuilder.
References ftorAdapter, randomizeParameters(), and scaleParameters().
void cb::RandomFunctorBuilder::parseParameter (const std::string & name, const std::string & value) virtual
Set a parameter.
An implementing function should parse the provided value and name string.
Parameters
name Parameter name string
value Parameter value string
Exceptions
InvalidNameError No parameter exists with the given name
InvalidValueError Parsed value is invalid (i.e. out of range)
Implements cb::Builder.
References C(), difficulty(), exponent(), R(), and x0().
Member Data Documentation
const std::string cb::RandomFunctorBuilder::parameterNames static private
Initial value:
= {
        "R",
        "C_x",
        "C_y",
        "x_0",
        "y_0",
        "e",
        "h"
}
The documentation for this class was generated from the following files:
src/cubmark/RandomFunctorBuilder.h
src/functions/RandomFunctorBuilder.cpp