Cubature benchmark: cb::HIntLibIntegrand Class Reference
cb::HIntLibIntegrand Class Reference
Adapter of function pointers to HIntLib::Integrand class.
#include <HIntLibIntegrand.h>
Public Member Functions
HIntLibIntegrand (int dimension)
Constructor.
~HIntLibIntegrand ()
Destructor.
unsigned long getCallCnt () const
Returns the number of calls off operator()
Method::IntegrandType getIntegrand () const
Returns the currently set integrand.
void resetCallCnt ()
Zero the call counter.
void setIntegrand (Method::IntegrandType integrand)
Change the integrand function.
HIntLib::real operator() (const HIntLib::real x[])
Static Private Member Functions
static double noop (double, double)
Private Attributes
Method::IntegrandType integrand
unsigned long callCnt
Detailed Description
Adapter of function pointers to HIntLib::Integrand class.
Constructor & Destructor Documentation
cb::HIntLibIntegrand::HIntLibIntegrand (int dimension) explicit
Constructor.
Required by the interface.
Parameters
dimension integrand dimension (ignored, always 2)
Member Function Documentation
unsigned long cb::HIntLibIntegrand::getCallCnt () const
Returns the number of calls off operator()
Returns
Number of calls to operator() since last call to reset_counter()
Referenced by cb::HIntLib::getCallCnt().
Method::IntegrandType cb::HIntLibIntegrand::getIntegrand () const
Returns the currently set integrand.
Returns
Pointer to currently set integrand or 0 if not set.
Referenced by cb::HIntLib::getIntegrand(), and cb::HIntLib::hasIntegrand().
void cb::HIntLibIntegrand::setIntegrand (Method::IntegrandType integrand)
Change the integrand function.
Parameters
integrand pointer to integrand function
The documentation for this class was generated from the following files:
src/cubmark/HIntLibIntegrand.h
src/method/HIntLibIntegrand.cpp