Cubature benchmark: cb::ResultQuality Class Reference
cb::ResultQuality Class Reference
Calculates the quality value, as defined by A. Genz.
#include <ResultQuality.h>
Public Member Functions
void compute (SamplesRangeType samples)
Compute the quality value for a sequence of samples.
virtual void write (ResultFormat &resultFormat) const
Pretty-print the result using a visitor.
double getQuality () const
Get calculated quality of the samples.
Private Attributes
double quality
Detailed Description
Calculates the quality value, as defined by A. Genz.
Member Function Documentation
void cb::ResultQuality::compute (SamplesRangeType samples) virtual
Compute the quality value for a sequence of samples.
Parameters
samples Samples to use for the statistic
Implements cb::ResultStatistic.
References cb::ResultMedian< Ret >::compute(), cb::Result::getCallCnt(), cb::Result::getRelativeError(), cb::Result::getRelativeErrorEstimate(), LOG, and cb::median().
double cb::ResultQuality::getQuality () const
Get calculated quality of the samples.
Returns
quality
void cb::ResultQuality::write (ResultFormat & format) const virtual
Pretty-print the result using a visitor.
Todo:
To avoid implementing this in every subclass consider writing a class template to mixin the definition.
Parameters
format Printing visitor
Reimplemented from cb::ResultStatistic.
The documentation for this class was generated from the following files:
src/cubmark/ResultQuality.h
src/views/statistics/ResultQuality.cpp