Cubature benchmark: cb::Boundary Class Reference
cb::Boundary Class Reference
Rectangular integral region class.
#include <Boundary.h>
Public Member Functions
Boundary ()
Default constructor.
Boundary (const std::string &boundaryStr)
Parse a boundary string.
Boundary (double a, double b, double c, double d)
Base constructor.
bool isValid () const
Is the boundary valid?
bool isInfinite () const
Is the boundary infinite in any axis?
bool isPlane () const
Does the boundary define an infinite (right) plane?
bool isRegular () const
Does the boundary define a square region?
void fillIn (const Boundary &boundary)
Fill in missing boundaries with values from another object.
const std::pair< double, double > & getLimits (size_t dim) const
double u (size_t dim) const
double l (size_t dim) const
void setLimits (size_t dim, const std::pair< double, double > &limits)
void setU (size_t dim, double u)
void setL (size_t dim, double l)
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Types
typedef std::vector< std::pair< double, double > > LimitsType
typedef std::vector< std::pair< bool, bool > > PlaceholdersType
Private Member Functions
void parseBoundaryStr (const std::string &boundaryStr)
Private Attributes
LimitsType limits
PlaceholdersType placeholders
Friends
class boost::serialization::access
Detailed Description
Rectangular integral region class.
Constructor & Destructor Documentation
cb::Boundary::Boundary (double a, double b, double c, double d)
Base constructor.
Initiates an object which represents a region
where
Precondition
a,b,c and d are not NaN
Parameters
a
b
c
d
Exceptions
std::runtime_exception When isnan() returns true for one of a, b, c, d.
Member Function Documentation
void cb::Boundary::fillIn (const Boundary & boundary)
Fill in missing boundaries with values from another object.
Parameters
boundary Replace missing values from this object
Returns
number of values taken from boundary
Referenced by cb::TestpackViewBuilder::create().
bool cb::Boundary::isInfinite () const
Is the boundary infinite in any axis?
Returns
True if either a, b, c or d equals inf or -inf.
Referenced by cb::G4Builder::integral(), cb::G3Builder::integral(), cb::G1Builder::integral(), cb::Dcuhre::setBoundary(), cb::MonteCarlo::setBoundary(), and cb::HIntLib::setBoundary().
bool cb::Boundary::isPlane () const
Does the boundary define an infinite (right) plane?
Returns
True if (a, b) = (-inf, inf) and (c, d) = (-inf, inf)
Referenced by cb::G4Builder::integral(), and cb::F1Builder::integral().
bool cb::Boundary::isRegular () const
Does the boundary define a square region?
Returns
True if (b - a) == (c - d)
Referenced by cb::F1Builder::integral().
bool cb::Boundary::isValid () const
Is the boundary valid?
Returns
True if none of the boundary parameters contain a NaN.
Referenced by cb::Dcuhre::hasBoundary(), cb::Qag2D::hasBoundary(), cb::HIntLib::hasBoundary(), cb::RandomFunctorBuilder::RandomFunctorBuilder(), cb::MonteCarlo::setBoundary(), cb::Cubpack::setBoundary(), cb::R2d2lri::setBoundary(), and cb::Adaptive::setBoundary().
The documentation for this class was generated from the following files:
src/cubmark/Boundary.h
src/Boundary.cpp
src/cubmark/Boundary.hpp