Cubature benchmark: cb::Adaptive Class Reference
cb::Adaptive Class Reference
Adaptive algorithm for non-adaptive cubature algorithms.
#include <Adaptive.h>
Classes
class NodeResult
class WorkPrioLess
Public Member Functions
Adaptive (Method *method, size_t subdivDepthLimit=10000)
Default constructor.
void setRelativeTolerance (double relativeTolerance)
Set requested relative cubature error tolerance.
double getRelativeTolerance () const
Get the currently set relative cubature error tolerance.
void setAbsoluteTolerance (double absoluteTolerance)
Set requested absolute cubature error tolerance.
double getAbsoluteTolerance () const
Get the currently set absolute cubature error tolerance.
void setBoundary (const Boundary &b)
Set a rectangular boundary.
bool hasBoundary () const
Check if this instance had a valid boundary set.
void setIntegrand (IntegrandType f)
Set the integrand to function F.
IntegrandType getIntegrand () const
Get the current integrand.
bool hasIntegrand () const
Check if this instance had an integrand set.
double compute ()
Evaluate the cubature.
bool failed () const
Did the last evaluation fail?
unsigned long getCallCnt () const
Get the number of integrand calls used by the last evaluation.
double getAbsoluteErrorEstimate () const
Get the absolute error estimate of the last cubature.
double getRelativeErrorEstimate () const
Get the absolute error estimate of the last cubature.
void setCallLimit (unsigned long max_calls)
Set the integrand call limit.
unsigned long getCallLimit () const
Get the integrand call limit.
Public Member Functions inherited from cb::Method
virtual ~Method ()
Destructor.
Private Types
typedef std::pair< size_t, Boundary > WorkUnitType
typedef std::pair< double, WorkUnitType > WorkPrioType
typedef std::priority_queue< WorkPrioType, std::deque< WorkPrioType >, WorkPrioLess > WorkQueueType
typedef std::map< size_t, NodeResult > ResultsType
Private Member Functions
double rangeMidpoint (double a, double b) const throw ()
Retrieve the midpoint of a range.
size_t subdivDepth (size_t address) const throw ()
Get a node's level in the quadtree.
size_t subdivParentAddress (size_t address) const throw ()
Calculate the address of the parent node.
size_t subdivChildAddress (size_t address) const throw ()
Calculate the address of the first child node.
bool isLeaf (size_t address) const
Is the node at addr a leaf?
bool isComplete (size_t address) const
Is the node at addr a parent to a complete branch?
void pruneCompleteNodes ()
Remove redundant subdivision results.
void queueSubdivisions (size_t address, const Boundary &boundary)
Queue subdivisions of a boundary for integration.
void gatherResults ()
Calculate the best cubature from the results in the quadtree.
void dumpResults ()
Dump the results in DOT format for debugging.
Private Attributes
std::auto_ptr< Method > worker
WorkQueueType workQueue
ResultsType results
Quadtree with evaluation results.
double cubature
double absErrEst
unsigned long callCnt
unsigned long callLimit
size_t subdivLimit
Static Private Attributes
static const unsigned long defaultCallLimit = 100000u
Additional Inherited Members
Public Types inherited from cb::Method
typedef double(* IntegrandType) (double, double)
Integrand function type.
Detailed Description
Adaptive algorithm for non-adaptive cubature algorithms.
This is an adapter for existing Method classes. The "worker" class is invoked on the region of integration. If the worker method fails, the region is divided along both axes and the worker object is invoked on each of the four subdivisions.
Infinite limits are supported as long as the worker class supports them.
Todo:
Check if the class could find a better result by searching the tree more thoroughly.
Todo:
If all subdivisions return a successful result, but the sum of their error estimates E exceeds the required tolerance, then the subdivision with the largest error estimate should be subdivided further.
  Let \form#0 denote the error estimate of the final result,
  where E_i is the error of the result of the i-th subdivision.
Constructor & Destructor Documentation
cb::Adaptive::Adaptive (Method * method, size_t subdivDepthLimit = 10000)
Default constructor.
Postcondition
Method object under the passed pointer will be deleted by the Adaptive object.
Parameters
method pointer to worker object. Cannot be NULL.
n Maximum number of subdivisions.
References LOG.
Member Function Documentation
double cb::Adaptive::compute () virtual
Evaluate the cubature.
Precondition
A boundary had been set with setBoundary()
Integrand had been set with setIntegrand()
Absolute or/and relative error tolerance had been set with setAbsoluteTolerance(), setRelativeTolerance()
Returns
Cubature value
Implements cb::Method.
References gatherResults(), LOG, pruneCompleteNodes(), queueSubdivisions(), and results.
void cb::Adaptive::gatherResults () private
Calculate the best cubature from the results in the quadtree.
Both the cubature and absolute error are the sum of the quadtree's leaves.
References isComplete(), and results.
Referenced by compute().
double cb::Adaptive::getAbsoluteErrorEstimate () const virtual
Get the absolute error estimate of the last cubature.
Returns
Absolute error estimate
Implements cb::Method.
Referenced by failed().
double cb::Adaptive::getAbsoluteTolerance () const virtual
Get the currently set absolute cubature error tolerance.
Returns
Current cubature error tolerance or 0.0 (unset)
Implements cb::Method.
Referenced by failed().
unsigned long cb::Adaptive::getCallCnt () const virtual
Get the number of integrand calls used by the last evaluation.
Returns
Number of integrand calls or 0 (no evaluation took place)
Implements cb::Method.
unsigned long cb::Adaptive::getCallLimit () const virtual
Get the integrand call limit.
Returns
Maximum number of allowed integrand function calls
Implements cb::Method.
Method::IntegrandType cb::Adaptive::getIntegrand () const virtual
Get the current integrand.
Returns
Pointer to integrand function
Implements cb::Method.
double cb::Adaptive::getRelativeErrorEstimate () const virtual
Get the absolute error estimate of the last cubature.
Returns
Absolute error estimate
Implements cb::Method.
Referenced by failed().
double cb::Adaptive::getRelativeTolerance () const virtual
Get the currently set relative cubature error tolerance.
Returns
Current relative cubature error tolerance or 0.0 (unset)
Implements cb::Method.
Referenced by failed().
bool cb::Adaptive::hasBoundary () const virtual
Check if this instance had a valid boundary set.
Returns
True if setBoundary() had been called with a valid Boundary object
Implements cb::Method.
bool cb::Adaptive::hasIntegrand () const virtual
Check if this instance had an integrand set.
Returns
True if setIntegrand() had been called
Implements cb::Method.
bool cb::Adaptive::isComplete (size_t address) const private
Is the node at addr a parent to a complete branch?
A parent with less than four children is incomplete.
Parameters
address Quadtree node address
References results, and subdivChildAddress().
Referenced by dumpResults(), gatherResults(), and pruneCompleteNodes().
bool cb::Adaptive::isLeaf (size_t address) const private
Is the node at addr a leaf?
Parameters
address Quadtree node address
References results, and subdivChildAddress().
Referenced by dumpResults().
void cb::Adaptive::pruneCompleteNodes () private
Remove redundant subdivision results.
This will remove results of nodes which won't be used in the final sum.
References isComplete(), and results.
Referenced by compute().
double cb::Adaptive::rangeMidpoint (double a, double b) const throw () private
Retrieve the midpoint of a range.
If the range is infinite then the "midpoint" will be at a point shifted by a constant value from the finite boudary or at 0.0
Parameters
a Left range boundary (can be -inf)
b Right range boundary (can be inf)
Referenced by queueSubdivisions().
void cb::Adaptive::setAbsoluteTolerance (double absoluteError) virtual
Set requested absolute cubature error tolerance.
Parameters
absoluteTolerance Absolute error tolerance or 0.0 (set method default)
Implements cb::Method.
void cb::Adaptive::setBoundary (const Boundary & boundary) virtual
Set a rectangular boundary.
Call with no arguments to clear the boundary.
Parameters
c Rectangular boundary object
Implements cb::Method.
References cb::Boundary::isValid().
void cb::Adaptive::setCallLimit (unsigned long callLimit) virtual
Set the integrand call limit.
The default is method-specific.
Parameters
max_calls Maximum number of allowed integrand function calls or (0 for default)
Implements cb::Method.
void cb::Adaptive::setIntegrand (IntegrandType f) virtual
Set the integrand to function F.
Parameters
f pointer to integrand function
Implements cb::Method.
void cb::Adaptive::setRelativeTolerance (double relativeError) virtual
Set requested relative cubature error tolerance.
Parameters
relativeTolerance Relative error tolerance or 0.0 (set method default)
Implements cb::Method.
size_t cb::Adaptive::subdivChildAddress (size_t address) const throw () private
Calculate the address of the first child node.
Parameters
addr Quadtree node address
Returns
Address of the first child node in the quadtree
Referenced by isComplete(), isLeaf(), and queueSubdivisions().
size_t cb::Adaptive::subdivDepth (size_t address) const throw () private
Get a node's level in the quadtree.
Parameters
addr Quadtree node address
Returns
Node level number
size_t cb::Adaptive::subdivParentAddress (size_t address) const throw () private
Calculate the address of the parent node.
Parameters
Quadtree node address
Returns
Address of the parent
Referenced by dumpResults().
Member Data Documentation
ResultsType cb::Adaptive::results private
Quadtree with evaluation results.
If a node has n < 4 children nodes, then those children should occupy n consecutive addresses beginning from the first child node.
For example: Parent at 0, n = 3 children Children will be at : 1,2,3 Not: 1,2,4 or 2,3,4
Failure to adhere to this scheme will break isComplete and isLeaf.
Referenced by compute(), dumpResults(), gatherResults(), isComplete(), isLeaf(), pruneCompleteNodes(), and queueSubdivisions().
The documentation for this class was generated from the following files:
src/cubmark/Adaptive.h
src/method/Adaptive.cpp