Cubature benchmark: cb::HistogramViewBuilder Class Reference
cb::HistogramViewBuilder Class Reference
Public Member Functions
void parseParameter (const std::string &name, const std::string &value)
Set a parameter.
void setXField (const std::string &xFieldName)
void setYField (const std::string &yFieldName)
void create (SuiteResults &results, std::ostream &ostream)
Create a view of the benchmark results.
Public Member Functions inherited from cb::Builder
virtual void parseDefinition (const Definition &definition)
Setup builder using a definition.
Private Types
typedef std::map< std::string, ResultStatistic * > FieldStatisticsType
Private Member Functions
void initResultFields ()
Private Attributes
ResultStatistic * xField
ResultStatistic * yField
std::string xLabel
std::string yLabel
std::string caption
FieldStatisticsType fieldStatistics
std::auto_ptr< ResultStatistic > rfArr [12]
Static Private Attributes
static const char * fieldNames [12]
Member Function Documentation
void cb::HistogramViewBuilder::create (SuiteResults & results, std::ostream & ostream) virtual
Create a view of the benchmark results.
Parameters
methodNames registered method names
suite benchmark suite
results results of the benchmark suite
Returns
a text view of benchmarking data
Implements cb::ViewBuilder.
void cb::HistogramViewBuilder::initResultFields () private
Todo:
These bits should be moved to a factory class
References cb::Result::getAbsoluteError(), cb::Result::getAbsoluteErrorEstimate(), cb::Result::getCallCnt(), cb::Result::getCpuTime(), cb::Result::getRelativeError(), cb::Result::getRelativeTolerance(), cb::Result::getResult(), cb::Result::isEfficient(), cb::Result::isErrorEstimationEfficient(), cb::Result::isFallibleMajor(), cb::Result::isFallibleMinor(), and cb::Result::isRobust().
void cb::HistogramViewBuilder::parseParameter (const std::string & name, const std::string & value) virtual
Set a parameter.
An implementing function should parse the provided value and name string.
Parameters
name Parameter name string
value Parameter value string
Exceptions
InvalidNameError No parameter exists with the given name
InvalidValueError Parsed value is invalid (i.e. out of range)
Implements cb::Builder.
References LOG.
Member Data Documentation
const char * cb::HistogramViewBuilder::fieldNames static private
Initial value:
=
{
        "efficiency",
        "errorEstimateEff",
        "robustness",
        "failMinor",
        "failMajor",
        "callCnt",
        "cpuTime",
        "bestResult",
        "bestAbsErrEst",
        "bestAbsErr",
        "bestRelErr",
        "ret"
}
The documentation for this class was generated from the following files:
src/cubmark/HistogramViewBuilder.h
src/views/HistogramViewBuilder.cpp