Cubature benchmark: cb::Qag2D Class Reference
cb::Qag2D Class Reference
QAG and QAGI product algorithm Adapter.
#include <Qag2D.h>
Public Member Functions
void setRelativeTolerance (double relativeTolerance)
Set requested relative cubature error tolerance.
double getRelativeTolerance () const
Get the currently set relative cubature error tolerance.
void setAbsoluteTolerance (double absoluteTolerance)
Set requested absolute cubature error tolerance.
double getAbsoluteTolerance () const
Get the currently set absolute cubature error tolerance.
void setBoundary (const Boundary &boundary)
Set a rectangular boundary.
bool hasBoundary () const
Check if this instance had a valid boundary set.
void setIntegrand (IntegrandType integrand)
Set the integrand to function F.
IntegrandType getIntegrand () const
Get the current integrand.
bool hasIntegrand () const
Check if this instance had an integrand set.
double compute ()
Evaluate the cubature.
bool failed () const
Did the last evaluation fail?
unsigned long getCallCnt () const
Get the number of integrand calls used by the last evaluation.
double getAbsoluteErrorEstimate () const
Get the absolute error estimate of the last cubature.
double getRelativeErrorEstimate () const
Get the absolute error estimate of the last cubature.
void setCallLimit (unsigned long callLimit)
Set the integrand call limit.
unsigned long getCallLimit () const
Get the integrand call limit.
Public Member Functions inherited from cb::Method
virtual ~Method ()
Destructor.
Private Attributes
int gsl_status
double absErrTol
double relErrTol
double absErrEst
double relErrEst
Boundary boundary
size_t callCnt
size_t callLimit
IntegrandType integrand
RuleChain2D ruleChain
Static Private Attributes
static const size_t defaultCallLimit = 100000u
Additional Inherited Members
Public Types inherited from cb::Method
typedef double(* IntegrandType) (double, double)
Integrand function type.
Detailed Description
QAG and QAGI product algorithm Adapter.
Integrate a 2D function using a tensor product of the QAG algorithms from the GSL library.
Integrates in the YX order. It would be equivalent to evulating an integral of the form:
Where is the integration region.
Member Function Documentation
double cb::Qag2D::compute () virtual
Evaluate the cubature.
Precondition
A boundary had been set with setBoundary()
Integrand had been set with setIntegrand()
Absolute or/and relative error tolerance had been set with setAbsoluteTolerance(), setRelativeTolerance()
Returns
Cubature value
Implements cb::Method.
References cb::RuleChain< DIM >::compute(), cb::QagRule::getAbsoluteErrorEstimate(), cb::RuleChain< DIM >::getRule(), cb::QagRule::setBoundary(), cb::QagRule::setDivisionLimit(), cb::QagRule::setEpsabs(), cb::QagRule::setEpsrel(), and cb::RuleChain< DIM >::setIntegrand().
double cb::Qag2D::getAbsoluteErrorEstimate () const virtual
Get the absolute error estimate of the last cubature.
Returns
Absolute error estimate
Implements cb::Method.
double cb::Qag2D::getAbsoluteTolerance () const virtual
Get the currently set absolute cubature error tolerance.
Returns
Current cubature error tolerance or 0.0 (unset)
Implements cb::Method.
unsigned long cb::Qag2D::getCallCnt () const virtual
Get the number of integrand calls used by the last evaluation.
Returns
Number of integrand calls or 0 (no evaluation took place)
Implements cb::Method.
References cb::RuleChain< DIM >::getCallCnt().
unsigned long cb::Qag2D::getCallLimit () const virtual
Get the integrand call limit.
Returns
Maximum number of allowed integrand function calls
Implements cb::Method.
Method::IntegrandType cb::Qag2D::getIntegrand () const virtual
Get the current integrand.
Returns
Pointer to integrand function
Implements cb::Method.
double cb::Qag2D::getRelativeErrorEstimate () const virtual
Get the absolute error estimate of the last cubature.
Returns
Absolute error estimate
Implements cb::Method.
double cb::Qag2D::getRelativeTolerance () const virtual
Get the currently set relative cubature error tolerance.
Returns
Current relative cubature error tolerance or 0.0 (unset)
Implements cb::Method.
bool cb::Qag2D::hasBoundary () const virtual
Check if this instance had a valid boundary set.
Returns
True if setBoundary() had been called with a valid Boundary object
Implements cb::Method.
References cb::Boundary::isValid().
bool cb::Qag2D::hasIntegrand () const virtual
Check if this instance had an integrand set.
Returns
True if setIntegrand() had been called
Implements cb::Method.
void cb::Qag2D::setAbsoluteTolerance (double absoluteError) virtual
Set requested absolute cubature error tolerance.
Parameters
absoluteTolerance Absolute error tolerance or 0.0 (set method default)
Implements cb::Method.
void cb::Qag2D::setBoundary (const Boundary & boundary) virtual
Set a rectangular boundary.
Call with no arguments to clear the boundary.
Parameters
c Rectangular boundary object
Implements cb::Method.
void cb::Qag2D::setCallLimit (unsigned long callLimit) virtual
Set the integrand call limit.
The default is method-specific.
Parameters
max_calls Maximum number of allowed integrand function calls or (0 for default)
Implements cb::Method.
void cb::Qag2D::setIntegrand (IntegrandType f) virtual
Set the integrand to function F.
Parameters
f pointer to integrand function
Implements cb::Method.
void cb::Qag2D::setRelativeTolerance (double relativeError) virtual
Set requested relative cubature error tolerance.
Parameters
relativeTolerance Relative error tolerance or 0.0 (set method default)
Implements cb::Method.
The documentation for this class was generated from the following files:
src/cubmark/Qag2D.h
src/method/Qag2D.cpp