Cubature benchmark: cb::Result Class Reference
cb::Result Class Reference
Benchmark result for a given method and test case.
#include <Result.h>
Public Member Functions
Result ()
Default constructor.
Result (const Result &)
Copy constructor.
virtual ~Result ()
Destructor.
bool isEfficient () const
Method efficiency.
bool isErrorEstimationEfficient () const
Error estimate efficiency.
bool isRobust () const
Method robustness.
bool isFailed () const
Was the incorrect result flagged as correct.
bool isFallibleMinor () const
Minor method fallibility.
bool isFallibleMajor () const
Major method fallibility.
double getCallCnt () const
Number of integrand calls.
double getCpuTime () const
Cpu time [ms].
double getResult () const
Estimated value of the integral.
double getAbsoluteErrorEstimate () const
Absolute error estimate of the result.
double getRelativeErrorEstimate () const
Absolute error estimate of the result.
double getAbsoluteError () const
Absolute error of the result.
double getRelativeError () const
Relative error of the result.
double getRelativeTolerance () const
Target relative tolerance for this result.
size_t getCase () const
Case index.
size_t getMethod () const
Method index.
std::string classification () const
Return a terse result classification string.
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Member Functions
Result (size_t caseIdx, size_t methodIdx, double I, double C, double relativeTolerance, double absoluteErrorEstimate, bool failureFlag, double cpuTimeMs, unsigned long callCnt)
Constructor for result of a single sample.
Private Attributes
size_t caseIdx
size_t methodIdx
bool efficiency
bool errorEstimationEfficiency
bool robustness
bool fallibilityMinor
bool fallibilityMajor
double callCnt
double cpuTime
double result
double absoluteErrorEstimate
double absoluteError
double relativeError
double relativeTolerance
Friends
class boost::serialization::access
class Benchmark
Detailed Description
Benchmark result for a given method and test case.
Constructor & Destructor Documentation
cb::Result::Result (size_t caseIdx, size_t methodIdx, double I, double C, double relativeTolerance, double absoluteErrorEstimate, bool failureFlag, double cpuTimeMs, unsigned long callCnt) private
Constructor for result of a single sample.
Parameters
caseIdx
methodIdx
I
C
relativeTolerance
absoluteErrorEstimate
failureFlag
cpuTimeMs
callCnt
References LOG.
Member Function Documentation
std::string cb::Result::classification () const
Return a terse result classification string.
Produce a terse string which classifies a result in several categories. Each character of the string represents a classification in a single category
{S|F} - Success / Failure (Positive / Negative result).
Determines how the method flagged the result.
{+|-|m|M} - Properly flagged / False negative / Minor failure / Major failure
Determines if the error was:
within the requested tolerance or properly flagged as a failure
within the requested tolerance but has been flagged as a failure
within an order of magnitude of the requested tolerance, but has been flagged as successful.
beyond an order of magnitude of the requested tolerance, but has been flagged as successful.
{e|E} - Real error smaller / greater than the method's estimate.
Examples (this isn't a comprehensive list):
"S+e" - Successful result with a good error estimate.
"S+E" - Successful result. Error estimate failure.
"F+e" - Negative result. The method failed to achieve the requested tolerance and reported a failure. The returned Result.had a good error estimate.
"SmE" - Minor evaluation failure. The method failed but reported a successful evaluation. The error estimate was off by less than an order of magnitude.
"SJE" - Major failure. The method failed but reported a successful evaluation. The error estimate was off by at least an order of magnitude.
"S-e" - False negative result. The method failed to recognize a successfully evaluated cubature. Error estimate within tolerance suggests a bug in error reporting code.
Parameters
r A benchmark result.
Returns
Classification string.
References isEfficient(), isErrorEstimationEfficient(), isFallibleMajor(), isFallibleMinor(), and isRobust().
bool cb::Result::isEfficient () const
Method efficiency.
This value is determined by comparing the exact analytic result to the method's result. The method's success/failure flag is ignored.
Referenced by classification(), and cb::HistogramViewBuilder::initResultFields().
bool cb::Result::isErrorEstimationEfficient () const
Error estimate efficiency.
Determines if the actual error fits within the error estimate reported by the method.
Referenced by classification(), and cb::HistogramViewBuilder::initResultFields().
bool cb::Result::isFailed () const
Was the incorrect result flagged as correct.
Returns
true if either isFailedMinor() or isFailedMajor() return true
References isFallibleMajor(), and isFallibleMinor().
bool cb::Result::isFallibleMajor () const
Major method fallibility.
Incorrect results flagged as successful, with the actual relative error beyond an order of magnitude of the tolerance.
Referenced by classification(), cb::HistogramViewBuilder::initResultFields(), and isFailed().
bool cb::Result::isFallibleMinor () const
Minor method fallibility.
Incorrect results flagged as successful, with the actual relative error within a single order of magnitude of the tolerance.
Referenced by classification(), cb::HistogramViewBuilder::initResultFields(), and isFailed().
bool cb::Result::isRobust () const
Method robustness.
Determines if the method can properly flag it's evaluation as failed and successful. A fallible method is a method which reports false negatives and false positives.
Referenced by classification(), and cb::HistogramViewBuilder::initResultFields().
The documentation for this class was generated from the following files:
src/cubmark/Result.h
src/cubmark/Result.hpp
src/Result.cpp