Cubature benchmark: cb::RuleChain< DIM > Class Template Reference
cb::RuleChain< DIM > Class Template Reference
Rule chain for multi-dimensional quadrature product integration.
#include <RuleChain.h>
Public Member Functions
RuleChain ()
Constructor.
void setIntegrand (Method::IntegrandType integrand)
Set the integrand.
QagRule & getRule (size_t dimension)
Access a rule object for a dimension.
const QagRule & getRule (size_t dimension) const
Access a rule object for a dimension.
unsigned long getCallCnt () const
Get the number of integrand calls used by the last evaluation.
double compute ()
Evaluate the cubature.
Private Types
typedef double(RuleChain::* ActionType) (double)
Private Member Functions
double evaluateIntegrand (double y)
Calls integrand with the coordinates stored in x.
double storeAndCallNext (double a)
Stores the point coordinate and calls the next rule in the chain.
double ruleActionDispatch (double a)
Call a function appropriate for the current dimension.
void initRuleActions ()
Initialize rule actions.
Private Attributes
ActionType ruleActions [DIM]
QagRule rules [DIM]
unsigned rulePos
Currently evaluated rule (dimension)
double x [DIM-1]
Array holding point coordinates.
unsigned long callCnt
Number of integrand evaluations.
Method::IntegrandType integrand
Friends
class ActionDispatch< DIM >
Detailed Description
template<int DIM = 2>
class cb::RuleChain< DIM >
Rule chain for multi-dimensional quadrature product integration.
NOTE: This class doesn't support more than 2 dimensions at this moment.
However it could be easily extended to handle N dimensions if the function type of cb::Method::IntegrandType were to be modified to use arrays. Then only evaluateIntegrand would require modififcation.
Member Function Documentation
template<int DIM> double cb::RuleChain< DIM >::compute ()
Evaluate the cubature.
Precondition
A boundary had been set with QagRule::setBoundary() for each rule in the chain
Integrand had been set with setIntegrand()
Absolute or/and relative error tolerance had been set for each rule in the chain with QagRule::setEpsabs() and QagRule::setEpsrel()
Returns
Cubature value
Referenced by cb::Qag2D::compute().
template<int DIM> double cb::RuleChain< DIM >::evaluateIntegrand (double y) private
Calls integrand with the coordinates stored in x.
Parameters
y Coordinate value for the last dimension
template<int DIM> unsigned long cb::RuleChain< DIM >::getCallCnt () const
Get the number of integrand calls used by the last evaluation.
Returns
Number of integrand calls or 0 (no evaluation took place)
Referenced by cb::Qag2D::getCallCnt().
template<int DIM> QagRule & cb::RuleChain< DIM >::getRule (size_t dimension)
Access a rule object for a dimension.
Parameters
dimension
Referenced by cb::Qag2D::compute(), and cb::Qag2D::failed().
template<int DIM> const QagRule & cb::RuleChain< DIM >::getRule (size_t dimension) const
Access a rule object for a dimension.
Parameters
dimension
template<int DIM> double cb::RuleChain< DIM >::ruleActionDispatch (double a) private
Call a function appropriate for the current dimension.
Calls storeAndCallNext() or evaluateIntegrand().
Parameters
a Coordinate value for the current dimension
template<int DIM> void cb::RuleChain< DIM >::setIntegrand (Method::IntegrandType integrand)
Set the integrand.
Parameters
integrand Integrand to use for the evaluation
Referenced by cb::Qag2D::compute().
template<int DIM> double cb::RuleChain< DIM >::storeAndCallNext (double a) private
Stores the point coordinate and calls the next rule in the chain.
Parameters
a Coordinate value for the current dimension
The documentation for this class was generated from the following files:
src/cubmark/RuleChain.h
src/cubmark/RuleChain.hpp