Cubature benchmark: cb::QagRule Class Reference
cb::QagRule Class Reference
Integration rule for a single dimension.
#include <QagRule.h>
Public Types
typedef double(* QagIntegrandType) (double, void *)
Public Member Functions
QagRule ()
Constructor.
~QagRule ()
Destructor.
void setDivisionLimit (size_t maxDiv)
Set the limit of subdivisions in this dimension.
void setBoundary (double a, double b)
Set the integration boundary.
void setEpsabs (double epsabs)
Set the desired absolute error tolerance.
void setEpsrel (double epsrel)
Set the desired relative error tolerance.
void setIntegrand (QagIntegrandType integrand)
Set the integrand to use.
double compute ()
Evaluate the integral for this dimension.
bool failed () const
Has the evaluation failed in this dimension.
double getAbsoluteErrorEstimate () const
Get the absolute error estimate.
Private Types
typedef int(QagRule::* RuleType) ()
Private Member Functions
RuleType chooseRule (double a, double b) const
Choose a QAG variant for the given boundary.
int qag ()
Integrates with gsl_integration_qag.
int qagi ()
Integrates with gsl_integration_qagi.
int qagiu ()
Integrates with gsl_integration_qagiu.
int qagil ()
Integrates with gsl_integration_qagil.
Private Attributes
RuleType rule
gsl_function F
gsl_integration_workspace * ws
int gsl_status
double a
double b
double epsabs
double epsrel
double result
double abserr
Detailed Description
Integration rule for a single dimension.
This class chooses QAG algorithm variant for integration based on the type of boundary set.
Member Function Documentation
double cb::QagRule::compute ()
Evaluate the integral for this dimension.
Use getAbsoluteErrorEstimate() to get the results error estimate in this dimension.
Returns
Cubature value in this dimension.
bool cb::QagRule::failed () const
Has the evaluation failed in this dimension.
Returns
Evaluation failed.
Referenced by cb::Qag2D::failed().
double cb::QagRule::getAbsoluteErrorEstimate () const
Get the absolute error estimate.
Returns
Absoluter error estimate of the last result.
Referenced by cb::Qag2D::compute().
int cb::QagRule::qag () private
Integrates with gsl_integration_qag.
Returns
gsl_status
Referenced by chooseRule().
int cb::QagRule::qagi () private
Integrates with gsl_integration_qagi.
Returns
gsl_status
Referenced by chooseRule().
int cb::QagRule::qagil () private
Integrates with gsl_integration_qagil.
Returns
gsl_status
Referenced by chooseRule().
int cb::QagRule::qagiu () private
Integrates with gsl_integration_qagiu.
Returns
gsl_status
Referenced by chooseRule().
void cb::QagRule::setBoundary (double a, double b)
Set the integration boundary.
Parameters
a Lower boundary
b Upper boundary
References chooseRule().
Referenced by cb::Qag2D::compute().
void cb::QagRule::setDivisionLimit (size_t maxDiv)
Set the limit of subdivisions in this dimension.
Parameters
max_div Maximum number of subdivisions
Referenced by cb::Qag2D::compute().
void cb::QagRule::setEpsabs (double epsabs)
Set the desired absolute error tolerance.
Parameters
epsabs Maximum absolute error
Referenced by cb::Qag2D::compute().
void cb::QagRule::setEpsrel (double epsrel)
Set the desired relative error tolerance.
Parameters
epsrel Maximum relative error
Referenced by cb::Qag2D::compute().
void cb::QagRule::setIntegrand (QagIntegrandType integrand)
Set the integrand to use.
Parameters
integrand Function to integrate.
The documentation for this class was generated from the following files:
src/cubmark/QagRule.h
src/method/QagRule.cpp