Cubature benchmark: cb::Definition Class Reference
cb::Definition Class Reference
Definition class.
#include <Definition.h>
Public Types
typedef std::deque< std::pair< std::string, std::string > > ParametersType
Public Member Functions
Definition ()
Default constructor.
Definition (const std::string &definitionStr)
Parse a definition string.
const std::string & getName () const
Get the name of the definition.
const ParametersType & getParameters () const
Get the parameter list of the definition.
std::string getString () const
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Member Functions
void parseDefinition (const std::string &definition)
Parse a definition string.
void parseParameters (const std::string &parametersStr)
Parse a parameter list string.
Private Attributes
std::string name
ParametersType parameters
Friends
class boost::serialization::access
Detailed Description
Definition class.
Class for tokenizing parameter strings. See the constructor documentation for input syntax.
Constructor & Destructor Documentation
cb::Definition::Definition (const std::string & definitionStr)
Parse a definition string.
A definition string is of the form:
name:parameter_list
An example of a test function definition could be: W3:n=3,C_x=2
A parameter list is of the form:
parameter_1,parameter_2,...,parameter_n
where each parameter is a pair of name and value
name[=value]
Parameters
definitionStr Definition string
References parseDefinition().
Member Function Documentation
const std::string & cb::Definition::getName () const
Get the name of the definition.
Returns
Name of the definition
const Definition::ParametersType & cb::Definition::getParameters () const
Get the parameter list of the definition.
Returns
Parameter list
Referenced by cb::Builder::parseDefinition().
void cb::Definition::parseDefinition (const std::string & definition) private
Parse a definition string.
Parameters
definition Definition string
References parseParameters().
Referenced by Definition().
void cb::Definition::parseParameters (const std::string & parametersStr) private
Parse a parameter list string.
Parameters
parametersStr parameter list
Referenced by parseDefinition().
The documentation for this class was generated from the following files:
src/cubmark/Definition.h
src/cubmark/Definition.hpp
src/Definition.cpp