Cubature benchmark: Setters for random parameters
Setters for random parameters
Functions
virtual RandomFunctorBuilder & cb::RandomFunctorBuilder::R (double R)
Set R parameter.
virtual RandomFunctorBuilder & cb::RandomFunctorBuilder::C (double C, unsigned long dim)
Set a scaling parameter.
virtual RandomFunctorBuilder & cb::RandomFunctorBuilder::x0 (double x0, unsigned long dim)
Set a DPS parameter.
void cb::RandomFunctorBuilder::randomizeParameters ()
Randomize parameters.
void cb::RandomFunctorBuilder::scaleParameters ()
Divide all parameters by the difficulty factor.
Variables
double cb::RandomFunctorBuilder::dR
General purpose parameter.
double cb::RandomFunctorBuilder::dC [2]
Scaling vector.
double cb::RandomFunctorBuilder::dx0 [2]
Point of Symmetry.
Detailed Description
These methods are called every time a parameter is about to change. They are declared virtual to allow subclasses to act on those changes for special purposes. For example, to use C as the upper boundary values instead of scaling, like the G1 test function.
If you override any of these, remember to forward the call back to it's superclass or the vectors won't be updated (unless you do not want them to change).
Function Documentation
RandomFunctorBuilder & cb::RandomFunctorBuilder::C (double C, unsigned long dim) protected virtual
Set a scaling parameter.
Parameters
C new value
dim dimension of the scaling parameter
Returns
Reference to this object
Reimplemented in cb::G1Builder, cb::G3Builder, and cb::W2Builder.
References cb::RandomFunctorBuilder::dC.
Referenced by cb::W2Builder::C(), cb::G3Builder::C(), cb::G1Builder::C(), cb::RandomFunctorBuilder::parseParameter(), and cb::RandomFunctorBuilder::randomizeParameters().
RandomFunctorBuilder & cb::RandomFunctorBuilder::R (double R) protected virtual
Set R parameter.
Parameters
R new value
Returns
Reference to this object
References cb::RandomFunctorBuilder::dR.
Referenced by cb::RandomFunctorBuilder::parseParameter(), and cb::RandomFunctorBuilder::randomizeParameters().
void cb::RandomFunctorBuilder::randomizeParameters () protected
Randomize parameters.
Difficulty factor and exponent remain unchanged.
References cb::RandomFunctorBuilder::C(), cb::RandomFunctorBuilder::R(), cb::urng01, and cb::RandomFunctorBuilder::x0().
Referenced by cb::RandomFunctorBuilder::create().
RandomFunctorBuilder & cb::RandomFunctorBuilder::x0 (double x0, unsigned long dim) protected virtual
Set a DPS parameter.
Set a coordinate of the Displaced Point of Symmetry.
Parameters
x0 new value
dim dimension of the displacement
Returns
Reference to this object
Reimplemented in cb::W2Builder, cb::W3Builder, and cb::W1Builder.
References cb::RandomFunctorBuilder::dx0.
Referenced by cb::RandomFunctorBuilder::parseParameter(), cb::RandomFunctorBuilder::randomizeParameters(), cb::W1Builder::x0(), cb::W2Builder::x0(), and cb::W3Builder::x0().