Cubature benchmark: Difficulty factor handling
Difficulty factor handling
Functions
virtual RandomFunctorBuilder & cb::RandomFunctorBuilder::exponent (double exponent)
Exponent parameter.
virtual RandomFunctorBuilder & cb::RandomFunctorBuilder::difficulty (double difficulty)
Difficulty parameter.
double cb::RandomFunctorBuilder::difficultyFactor () const
Calculate the current difficulty factor.
Detailed Description
Manipulate the difficulty setting.
Function Documentation
RandomFunctorBuilder & cb::RandomFunctorBuilder::difficulty (double difficulty) virtual
Difficulty parameter.
Denoted as in literature.
Parameters
difficulty New value of the difficulty parameter
Returns
Reference to this object
Referenced by cb::RandomFunctorBuilder::parseParameter().
double cb::RandomFunctorBuilder::difficultyFactor () const protected
Calculate the current difficulty factor.
Returns
Difficulty factor
References cb::RandomFunctorBuilder::dC.
Referenced by cb::G1Builder::C(), cb::G3Builder::C(), and cb::RandomFunctorBuilder::scaleParameters().
RandomFunctorBuilder & cb::RandomFunctorBuilder::exponent (double exponent) virtual
Exponent parameter.
Denoted as in literature.
Parameters
exponent New value of the exponent
Returns
Reference to this object
Referenced by cb::RandomFunctorBuilder::parseParameter().