Cubature benchmark: cb Namespace Reference
cb Namespace Reference
Main namespace of the Benchmark suite.
Classes
class ActionDispatch
class Adapter
Adapter class template for binary functions.
class Adapter<-1, FO, R, A...>
Recursive template instantiation NullAdapter for binary function template.
class AdapterBase
Common interface dependent on function pointer type.
class AdapterFtorBase
Common functor type dependent methods.
class AdapterLock
Adapter lock template class.
class AdapterManager
Adapter manager template class.
class AdapterManagerBase
Adapter manager template class.
class AdapterSlot
class AdapterTraits
Adapter traits.
class AdapterTraits< Constant, R, A...>
class Adaptive
Adaptive algorithm for non-adaptive cubature algorithms.
class Benchmark
Class for evaluating benchmarks.
struct BinaryAdapter
Convienence template for binary STL-like functors.
class Boundary
Rectangular integral region class.
class Builder
Common class for all builders.
class CaseResults
Benchmark result for a given method and test case.
class CaseSpecification
struct compile_time_checker
Static assertion checker.
struct compile_time_checker< false >
Static assertion checker.
class Constant
Boundary function functor.
class Cubpack
Cubpack++ algorithm Adapter.
struct CubpackIntegrand
Cubpack++ function Adapter.
class Dcuhre
class DcuhreIntegrand
DCUHRE function Adapter.
class Definition
Definition class.
class F1
Test function 1.
class F1Builder
class Factory
class FieldLess
Comparison functor for use with STL algorithms.
class FullViewBuilder
struct FuncPtr
Function pointer typedef template.
class G1
Genz "Oscillatory" test function.
class G1Builder
class G2
Genz "Product peak" test function.
class G2Builder
class G3
Genz "Corner peak" test function.
class G3Builder
class G4
Genz "Gaussian" test function.
class G4Builder
class G5
Genz "C0" test function.
class G5Builder
class G6
Genz "Discontinuous" test function.
class G6Builder
class HIntLib
HIntLib library Adapter.
class HIntLibIntegrand
Adapter of function pointers to HIntLib::Integrand class.
class HistogramViewBuilder
class IncompleteError
The object being built is incomplete.
class InvalidNameError
No parameter exists with that name.
class InvalidValueError
Parameter value is invalid.
class KahanSum
Calculate the Kahan sum of a floating point sequence.
class less
Comparison functor for use with STL algorithms.
class LogManager
Simple log manager.
class Method
Common interface for all cubature methods.
class MethodFactory
Factory class for Methods.
class MonteCarlo
GSL MonteCarlo algorithm Adapter.
struct MonteCarloIntegrand
class NullAdapter
Recursive template instantiation guardian.
class NullOstream
Output stream to /dev/null.
class P1Builder
class Qag2D
QAG and QAGI product algorithm Adapter.
class QagRule
Integration rule for a single dimension.
class QP1
QP1 test function.
class QP1Builder
class R2d2lri
r2d2lri algorithm Adapter
class RandomFunctorBuilder
class RawViewBuilder
class RD28Builder
class RD29Builder
class RD31Builder
class RD35Builder
class Result
Benchmark result for a given method and test case.
class ResultAccumulate
class ResultAverage
class ResultFormat
Pretty-printer for result statistics.
class ResultMedian
class ResultQuality
Calculates the quality value, as defined by A. Genz.
class ResultQuantiles
class ResultSelect
class ResultStatistic
Sample result processing interface.
class RuleChain
Rule chain for multi-dimensional quadrature product integration.
struct Sample
Benchmark case class.
class Scanner
class Scanner< double, char >
class Singleton
class StopTimer
Class for runtime measuring.
class SuiteResults
Container for Benchmark suite results.
class SuiteSpecification
class TestFunctorBuilder
Interface for functor builders with command-line parameters.
class TestFunctorFactory
class TestpackViewBuilder
class TraceMethod
Tracing shim for concrete Method classes.
struct UnaryAdapter
Convienence template for binary STL-like functors.
class ViewBuilder
class ViewFactory
class W1
Analitic form of the wigner function for a constant wavefunction.
class W1Builder
struct W1WaveFunc
Wavefunction for testing with cb::wigner.
class W2
Analitic form of the wigner function for a triangular wavefunction.
class W2Builder
struct W2WaveFunc
Wavefunction for testing with cb::wigner.
struct W3
Analytic form of W_n(x,k) for an infinite potential well.
class W3Builder
struct W3WaveFunc
Wavefunction for testing with cb::wigner.
struct WavefuncIntegrand
class Wigner
Wigner functor class.
class WignerBuilder
Typedefs
typedef cb::QP1 P1
P1 test function.
typedef RuleChain< 2 > RuleChain2D
Rule chain for 2D integration.
typedef std::deque< Result > SamplesType
typedef std::pair< SamplesType::iterator, SamplesType::iterator > SamplesRangeType
typedef std::pair< SamplesType::const_iterator, SamplesType::const_iterator > ConstRangeType
Enumerations
enum MethodIdType {
M_R2D2LRI, M_CUBPACKPP, M_ADAPT_R2D2LRI, M_HINTLIB,
M_GSL_MONTECARLO, M_GAUSS_PRODUCT, M_DCUHRE
}
enum TestFunctorIdType {
F_G1, F_G2, F_G3, F_G4,
F_G5, F_G6, F_W1, F_W2,
F_W3, F_F1, F_QP1, F_P1,
F_RD28, F_RD29, F_RD31, F_RD35
}
enum ViewIdType { V_RAW, V_FULL, V_HISTOGRAM, V_TESTPACK }
Functions
template<class FO , class R , class... A>
void adapterSetFunctor (AdapterBase< R, A...> *adapter, const FO &functor)
template<class FO , class R , class... A>
void adapter (AdapterBase< R, A...> *&ftorAdapter)
template<class FO , class R , class... A>
void adapter (AdapterFtorBase< FO, R, A...> *&ftorAdapter)
template<class UF >
AdapterBase< typename UF::result_type, typename UF::argument_type > * adapter (const UF &stlUnaryFunctor)
Convienience function template for acquiring adapter locks to STL-style unary functors.
template<class BF >
AdapterBase< typename BF::result_type, typename BF::first_argument_type, typename BF::second_argument_type > * adapter (const BF &stlBinaryFunctor)
Convienience function template for acquiring adapter locks to STL-style binary functors.
template<class It , class LessOp >
std::pair< It, It > median (It begin, It end, LessOp lessOp)
Calculate the median element of a sequence.
template<class It >
std::pair< It, It > median (It begin, It end)
template<class It , class LessOp >
std::vector< std::pair< It, It > > quantiles (It begin, It end, unsigned q, LessOp lessOp=std::less< typename It::value_type >())
Calculate the q-quantiles of a sequence.
template<class T >
std::vector< std::pair< T *, T * > > quantiles (T *begin, T *end, unsigned q, std::less< T > lessOp=std::less< T >())
template<class Ret , Ret(Result::*)() const MemFun, class It >
It minField (It begin, It end)
template<class F >
int fcmp (const F x1, const F x2)
Compare two floating point numbers.
template<class F >
bool feq (const F x1, const F x2)
template<class F >
int fcmp0 (const F x)
template<class F >
bool feq0 (const F x1)
template<class T >
std::pair< T *, T * > median (T *begin, T *end, std::less< T > lessOp=std::less< T >())
template<class E >
void CHECK_ (bool expression, const E &exception, const char *prefix) throw ()
void CHECK_ (bool expression, const char *error_message, const char *prefix="") throw ()
Assertion check w/o exceptions.
template<typename CharT , typename Traits >
NullOstream< CharT, Traits > & operator<< (NullOstream< CharT, Traits > &out, CharT)
template<typename CharT , typename Traits >
NullOstream< CharT, Traits > & operator<< (NullOstream< CharT, Traits > &out, char)
template<typename CharT , typename Traits >
NullOstream< CharT, Traits > & operator<< (NullOstream< CharT, Traits > &out, const CharT *)
template<typename CharT , typename Traits >
NullOstream< CharT, Traits > & operator<< (NullOstream< CharT, Traits > &out, const char *)
template<typename CharT , typename Traits >
NullOstream< CharT, Traits > & endl (NullOstream< CharT, Traits > &os)
template<typename CharT , typename Traits >
NullOstream< CharT, Traits > & ends (NullOstream< CharT, Traits > &os)
template<typename CharT , typename Traits >
NullOstream< CharT, Traits > & flush (NullOstream< CharT, Traits > &os)
template<class R , class T >
ResultAccumulate< R, T > * resultAccumulate (unsigned q, T(Result::*)() const)
template<class T >
ResultAccumulate< T, T > * resultAccumulate (unsigned q, T(Result::*)() const)
template<class Ret , class T >
ResultAccumulate< Ret, T > * resultAccumulate (unsigned q, T(Result::*memberFunction)() const)
template<class T , class F >
ResultAverage< T, F > * resultAverage (F(Result::*)() const)
template<class T >
ResultAverage< T, T > * resultAverage (T(Result::*)() const)
std::ostream & operator<< (std::ostream &output, const ResultStatistic &result)
template<class T >
ResultMedian< T > * resultMedian (T(Result::*)() const)
template<class Ret >
ResultMedian< Ret > * resultMedian (Ret(Result::*memberFunction)() const)
template<class R , class T >
ResultQuantiles< R, T > * resultQuantiles (unsigned q, T(Result::*)() const)
template<class T >
ResultQuantiles< T, T > * resultQuantiles (unsigned q, T(Result::*)() const)
template<class Ret , class T >
ResultQuantiles< Ret, T > * resultQuantiles (unsigned q, T(Result::*memberFunction)() const)
template<class T , class A >
ResultSelect< T, A > * resultFind (T(Result::*memberFunction)() const, A algorithm)
template<class Ret , class Algo >
ResultSelect< Ret, Algo > * resultSelect (Ret(Result::*memberFunction)() const, Algo algorithm)
double K (double a, double b, double C, double x_0)
Variables
static const double NaN = std::numeric_limits<double>::quiet_NaN()
static const double sNaN = std::numeric_limits<double>::signaling_NaN()
static const double inf = std::numeric_limits<double>::infinity()
static const double eps = std::numeric_limits<double>::epsilon()
static const double PI = static_cast<double>(4.0l * atanl(1.0l))
tr1::random_device urng
Random integer number generator.
tr1::ranlux48 urng01
High-quality random double-precision number generator.
Detailed Description
Main namespace of the Benchmark suite.
Typedef Documentation
typedef cb::QP1 cb::P1
P1 test function.
The only difference between P1 and QP1 are their test integrals and the c parameter.
Proper integral:
where
Function Documentation
template<class UF > AdapterBase<typename UF::result_type, typename UF::argument_type>* cb::adapter (const UF & stlUnaryFunctor)
Convienience function template for acquiring adapter locks to STL-style unary functors.
See cb::UnaryAdapter on how to instantiate a lock from the lock handle. See adapter_function_template_stl.cpp for example code.
Template Parameters
UF unary functor class deduced from argument The class can be derived from std::unary_function.
Parameters
f Functor instance
template<class BF > AdapterBase<typename BF::result_type, typename BF::first_argument_type, typename BF::second_argument_type>* cb::adapter (const BF & stlBinaryFunctor)
Convienience function template for acquiring adapter locks to STL-style binary functors.
See cb::BinaryAdapter on how to instantiate a lock from the lock handle. See adapter_function_template_stl.cpp for example code.
Template Parameters
BF binary functor class deduced from argument The class can be derived from std::binary_function.
Parameters
f Functor instance
void cb::CHECK_ (bool expression, const char * error_message, const char * prefix = "") throw ()
Assertion check w/o exceptions.
This function prints exception.what() and calls exit() instead of actually throwing the exception.
Parameters
expression expression to check
exception pseudo-exception to throw when expression is false
prefix Prefix inserted before the error message. See CUBMARK_LOG_PREFIX
Template Parameters
E pseudo-exception class
template<class F > int cb::fcmp (const F x1, const F x2) inline
Compare two floating point numbers.
Based on gsl_fcmp copyright (C) 20002 Gert Van den Eynde
Which in turn is based on fcmp 1.2.2 Copyright (c) 1998-2000 Theodore C. Belding
template<class It , class LessOp > std::pair< It, It > cb::median (It begin, It end, LessOp lessOp)
Calculate the median element of a sequence.
This algorithm is as fast as std::nth_element. (which is implied to have O(n) time complexity but reorders the sequence)
Parameters
begin Beginning of the sequence
end End of a sequence
lessOp Instance of an ordering operator
Template Parameters
It RandomAccessIterator
LessOp ordering operator
Returns
Iterators pointing to elements that make up the median or make_pair(median, end)
References quantiles().
Referenced by cb::ResultMedian< Ret >::compute(), and cb::ResultQuality::compute().
template<class It , class LessOp > std::vector< std::pair< It, It > > cb::quantiles (It begin, It end, unsigned q, LessOp lessOp = std::less<typename It::value_type>())
Calculate the q-quantiles of a sequence.
This algorithm is as fast as std::nth_element. (which is implied to have O(n) time complexity but reorders the sequence)
Parameters
begin Beginning of the sequence
end End of a sequence
q
lessOp Instance of an ordering operator
Template Parameters
It RandomAccessIterator
LessOp ordering operator
Returns
vector of pairs of iterators, each pointing to a quantile or elements surrounding the median (see cb::median)
Referenced by cb::ResultQuantiles< Ret, T >::compute(), and median().
Variable Documentation
tr1::random_device cb::urng
Random integer number generator.
Defaults to mt19937 if the platform does not supply a random device.
tr1::ranlux48 cb::urng01
High-quality random double-precision number generator.
Generates random numbers from the [0,1) range.
Referenced by cb::RandomFunctorBuilder::randomizeParameters().